POST /api/blog/ HTTP/1.1
Host: localhost:3003
Content-Type: application/json

{
    "title":"My third blog entry in MongoDB and React!",
    "author":"MPC",
    "url":"http://localhost:3003/api/blogs/3",
    "likes":8
}